from typing import Tuple, Optional, Dict, Any
from termcolor import colored
import importlib.util

from .base_provider import BaseProvider
from .response_parser import ResponseParser

class OpenAIProvider(BaseProvider):
    """OpenAI API provider"""
    
    def __init__(self):
        self.client = None
        self.model = None
        
    @property
    def name(self) -> str:
        return "openai"
    
    @property
    def description(self) -> str:
        return f"OpenAI ({self.model})" if self.model else "OpenAI"
    
    def initialize(self, config: Dict[str, Any]) -> bool:
        """Initialize OpenAI with configuration"""
        try:
            # Check if OpenAI package is installed
            if importlib.util.find_spec("openai") is None:
                print(colored("⚠️ OpenAI package not installed. Run 'pip install openai'", "yellow"))
                return False
                
            import openai
            api_key = config.get("api_key")
            base_url = config.get("base_url")
            self.model = config.get("model")
            
            if not api_key:
                print(colored("⚠️ OpenAI API key not configured", "yellow"))
                return False
                
            client_args = {"api_key": api_key}
            if base_url:
                client_args["base_url"] = base_url
                
            self.client = openai.OpenAI(**client_args)
            
            # Test connection with a simple request
            model = self.model or "gpt-3.5-turbo"
            response = self.client.chat.completions.create(
                model=model,
                messages=[{"role": "user", "content": "Hi"}],
                max_tokens=5
            )
            
            # Set the model if not already set
            if not self.model:
                self.model = "gpt-3.5-turbo"
                
            print(colored(f"✓ OpenAI initialized successfully with model {model}", "green"))
            return True
            
        except Exception as e:
            print(colored(f"⚠️ OpenAI initialization failed: {str(e)}", "yellow"))
            return False
    
    def generate_command(self, user_input: str, os_type: str) -> Tuple[Optional[str], Optional[str]]:
        """Generate command using OpenAI"""
        if not self.client:
            return None, None
            
        try:
            system_prompt = f"""You are a {os_type} terminal expert. Follow STRICTLY:
                1. Respond with ONLY the executable command on FIRST LINE
                2. Use Windows cmd commands when target is windows
                3. Use bash commands when target is linux/mac
                4. Current system: {os_type}
                5. Example Windows alternatives:
                   - clear -> cls
                   - ls -> dir
                   - grep -> findstr"""
                
            response = self.client.chat.completions.create(
                model=self.model or "gpt-3.5-turbo",
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": f"Convert to terminal command: {user_input}\n\nCommand:"}
                ],
                temperature=0.5
            )
            
            if not response.choices:
                return None, None
                
            full_response = response.choices[0].message.content
            command, explanation = ResponseParser.parse_response(full_response)
            
            return command, explanation if explanation else f"Generated by OpenAI ({self.model})"
            
        except Exception as e:
            print(colored(f"⚠️ OpenAI API Error: {str(e)}", "red"))
            return None, None
